### ISSUE TITLE
ElasticSearch and its expected date formats

### ISSUE THREAD

**Issue by Karm** [intfeed/sinkit-core#36]
We should set this straight :disappointed: 

    SEVERE [biz.karms.sinkit.ejb.elastic.ElasticServiceEJB] (default task-14) Archive returned error: MapperParsingException[mapping [match]]; nested: IllegalArgumentException[Invalid format: [yyyy-MM-ddTHH:mm:ssZ]: Illegal pattern component: T]; nested: IllegalArgumentException[Illegal pattern component: T]; 
    SEVERE [biz.karms.sinkit.ejb.DNSApiEJB] (default task-14) getSinkHole: Logging BLOCK failed: : biz.karms.sinkit.exception.ArchiveException: MapperParsingException[mapping [match]]; nested: IllegalArgumentException[Invalid format: [yyyy-MM-ddTHH:mm:ssZ]: Illegal pattern component: T]; nested: IllegalArgumentException[Illegal pattern component: T]; 
    at biz.karms.sinkit.ejb.elastic.ElasticServiceEJB.index(ElasticServiceEJB.java:169)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)

in ```EventLogRecord```, you expect Date, so I give you ```eventLogRecord.setLogged(Calendar.getInstance().getTime());```. What's going on with Elastic's formatter? Could you fix it pls?

**Comment by kozeltom** [comment]
Where and why do you access an instance of  EventLogRecord directly? You should only call method logEvent in CoreServiceEJB...

**Comment by kozeltom** [comment]
@robcza, can you pls check the definition of field "logged" of log record in Elastic? The pattern  yyyy-MM-ddTHH:mm:ssZ is wrong and it should be yyyy-MM-dd'T'HH:mm:ssZ. I think we have been solving this issue already...

**Comment by Karm** [comment]
@kozeltom @robcza I cannot see the issue anymore :hammer: Which is kinda weird :point_up_2:

**Comment by robcza** [comment]
Could have been an issue on the elastic index mapping side. Give it a try a few more times and should it work, close this issue.

**Comment by kozeltom** [comment]
Can I close it? It makes me go crazy this time format issues...

**Comment by Karm** [comment]
Closing...
