### ISSUE TITLE
Search returned 2 hits. Expecting max one -> panic!

### ISSUE THREAD

**Issue by Karm** [intfeed/sinkit-core#60]
See [logs](http://fpaste.org/286239/44650216/).
Infamous ```2 hits``` problem followed by ```Caused by: java.net.SocketTimeoutException: Read timed out```.

Branch: [Karm: interfaces-and-deactivator](https://github.com/Karm/sinkit-core/tree/interfaces-and-deactivator) Might not contain Kozlik's last fix.

**Comment by robcza** [comment]
I guess this one is already obsolete. @kozeltom should be the one to close this I guess

**Comment by kozeltom** [comment]
Resolved by new elastic IDs approach.
