### ISSUE TITLE
No REST method to create new customer

### ISSUE THREAD

**Issue by rattuscz** [intfeed/sinkit-core#63]
When using **PUT** /rules/customer/<id> is only way to put customer specific rules in place, but fails if customer is not recognized -> new customer rules cannot be inserted this way.

Only other option is to use /rules/all which would be silly to use each time new customer is added.

Either allow PUT for nonexisting customer or make new PUT/POST API call for creating new customer

**Comment by Karm** [comment]
@rattuscz  @robcza  See #68 for details. It is possible to do what Rattus asked for, IMHO.

**Comment by robcza** [comment]
@rattuscz satisfied with this solution? if yes, close this issue please

**Comment by rattuscz** [comment]
Yes, checked yesterday.
